package edu.funix.Utils;

public enum PageType {
	POST_MANAGEMENT_PAGE, NEW_POST, EDIT_POST, 
	CATEGORY_MANAGEMENT_PAGE, EDIT_CATEGORY,
	USER_MANAGEMENT_PAGE, NEW_USER, EDIT_USER,
	COMMENT_MANAGEMENT_PAGE,
	LOGIN, REGISTER, HOMEPAGE, POST_DETAIL
}
