package edu.funix.Utils;

public enum PageType {
    	ACCESS_DENIED, LOGIN_ALREADY,
	POST_MANAGEMENT_PAGE, NEW_POST, EDIT_POST, 
	CATEGORY_MANAGEMENT_PAGE, EDIT_CATEGORY,
	USER_MANAGEMENT_PAGE, NEW_USER, EDIT_USER,
	SUBCRIBER_MANAGEMENT_PAGE,
	COMMENT_MANAGEMENT_PAGE,
	LOGIN, REGISTER, PASSWORD_CHANGE, FORGOT_PASSWORD,
	HOMEPAGE, POST_DETAIL
}
