USE master;
GO
IF DB_ID (N'CMS_Project') IS NOT NULL
DROP DATABASE CMS_PROJECT;
GO
CREATE DATABASE CMS_PROJECT;
GO

USE CMS_PROJECT
GO

CREATE TABLE tblUSER (
	UserID SMALLINT IDENTITY(1,1) PRIMARY KEY,
	Username VARCHAR(75) UNIQUE NOT NULL,
	UserMail VARCHAR(75) UNIQUE NOT NULL,
	Pwd VARCHAR(50) NOT NULL,
	DisplayName VARCHAR(90) NULL,
	Register Date NOT NULL,
	UserRole TINYINT NOT NULL,
	Promoted SMALLINT FOREIGN KEY REFERENCES tblUSER(UserID) NULL,
)

CREATE TABLE tblMEDIA (
	MediaID SMALLINT IDENTITY(1,1) PRIMARY KEY,
	MediaTitle NVARCHAR(90) UNIQUE NOT NULL,
	CreateDate DATE DEFAULT getdate() NOT NULL,
	MediaURL VARCHAR(150) UNIQUE NOT NULL,
	UploadBy SMALLINT FOREIGN KEY REFERENCES tblUSER(UserID) NOT NULL
)

CREATE TABLE tblPOST (
	PostID SMALLINT IDENTITY(1,1) PRIMARY KEY,
	PostTitle NVARCHAR(150) UNIQUE NOT NULL,
	Excerpt NVARCHAR(300) NULL,
	Content NVARCHAR(4000) NULL,
	PostURL VARCHAR(150) NOT NULL,
	CreateDate DATE DEFAULT GetDate() NOT NULL,
	PublishDate DATE NULL,
	ModifyDate DATE NULL,
	PostStatus TINYINT DEFAULT 0 NOT NULL,
	IsVisible BIT DEFAULT 0 NOT NULL,
	Author SMALLINT FOREIGN KEY REFERENCES tblUSER(UserID),
	Editor SMALLINT FOREIGN KEY REFERENCES tblUSER(UserID),
	Feature SMALLINT FOREIGN KEY REFERENCES tblMEDIA(MediaID)
)

CREATE TABLE tblCATEGORY (
	CatID TINYINT IDENTITY(1,1) PRIMARY KEY,
	CatName NVARCHAR(75) UNIQUE NOT NULL,
	CatURL VARCHAR(150) UNIQUE NOT NULL,
	CatDesc NVARCHAR(300) NULL,
)

CREATE TABLE tblPOSTGROUP (
	CatID TINYINT FOREIGN KEY REFERENCES tblCATEGORY(CatID),
	PostID SMALLINT FOREIGN KEY REFERENCES tblPOST(PostID),
	CONSTRAINT PK_PostGroup PRIMARY KEY (CatID, PostID)
)

CREATE TABLE tblCOMMENT (
	ComID INT IDENTITY(1,1) PRIMARY KEY,
	ComContent NVARCHAR(150) NOT NULL,
	CreateDate DATE DEFAULT getdate() NOT NULL,
	SubmitBy SMALLINT FOREIGN KEY REFERENCES tblUSER(UserID) NOT NULL,
	SubmitTo SMALLINT FOREIGN KEY REFERENCES tblPOST(PostID) NOT NULL,
	ReplyTo INT FOREIGN KEY REFERENCES tblCOMMENT(ComID) NULL,
	Confirm BIT DEFAULT 0 NOT NULL
)

CREATE TABLE tblOPTION (
	OptName VARCHAR(100) PRIMARY KEY,
	OptValue VARCHAR(150) NOT NULL
)